### ISSUE TITLE
[Bug]: The Website isn't responsive for small layouts

### ISSUE THREAD

**Issue by execrc** [apu52/Stopwatch-maker#2]
# Steps to Reproduce-
1. Go to 'Website home page'
2. Go to  'Inspect Element'
3. Change the layout for small devices  'Set width below 400px'

![image](https://github.com/apu52/Stopwatch-maker/assets/129402570/20e865b6-6465-4432-939d-a5a569fd3b68)

# Expected Behavior 
Website must be responsive for small devices

**Comment by apu52** [comment]
Welcome to My repository. Don't forget to make a pull request after fixing the bugs. Thanks for opening my issue here! Be sure to follow the issue template and also star the repository so that you don't miss out with it!
